// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_chooselevelscene.cpp"
#include "EWIEGA46WW/moc_coin.cpp"
#include "EWIEGA46WW/moc_mainscene.cpp"
#include "EWIEGA46WW/moc_mydialog.cpp"
#include "EWIEGA46WW/moc_mylabel.cpp"
#include "EWIEGA46WW/moc_mypushbutton.cpp"
#include "EWIEGA46WW/moc_playscene.cpp"
